In [2]:
list_2=list(range(1,4))#1,2,3 =>is a list
list_3=list(range(1,4))
list_sum=[]
for index in range(3):
    list_2[index]  = list_2[index] ** 2
    list_3[index] = list_3[index] ** 3
    list_sum.append(list_2[index] + list_3[index])
print(list_sum)

[2, 12, 36]


In [10]:
#Simpler version of the above python code using numpy

import numpy as np#all submodules and functions from numpy under alis np
a1=np.arange(1,4) **2#start=1,end=4=>array(not list) from 1 to 3
print(a1)#[1 4 9]
a2=np.arange(1,4)**3
print(a2)#[ 1  8 27]
print(a1+a2)#[ 2 12 36]=>vectorized addition of individual element of array


[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [13]:
np.power(np.array([1,2,3]) , 4) #array([ 1, 16, 81])
np.array([1,2,3]) **4 #array([ 1,  8, 27])=>same as above


array([ 1,  8, 27])

In [15]:
test=np.array([1,2,3])
print(np.exp(test))
print(np.log(test))
print(np.sin(test))
print(np.cos(test))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [19]:
#slicing 1D arrays
x=np.arange(1,10)#indexing is same from 0
print(x)
print(x[2:7:2])
print(x[2:])# element 3 is index 2

[1 2 3 4 5 6 7 8 9]
[3 5 7]
[3 4 5 6 7 8 9]


In [26]:
#reshape 1D to a 2D array
t=np.arange(18).reshape(2,3,3)=>2D arrays both 3 by 3 size with 9 elements each
print(t)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
