In [10]:
import numpy as np
x= np.arange(3)#start by default 0->array from 0 to 2
y= np.arange(3)
z= np.arange(3)
twoD_array=np.array([x,y,z])
print(twoD_array)#[[0 1 2]
                 #   [0 1 2]
                  #  [0 1 2]]
        
print(twoD_array[0,1])#1

print(twoD_array.shape)#(3, 3)

twoD_array2=np.array([x,y,z],dtype= np.uint8)
print(twoD_array2.dtype)#data type =>bigger size for scientific computing

[[0 1 2]
 [0 1 2]
 [0 1 2]]
1
(3, 3)
uint8


In [6]:
w=  np.linspace(1,10,50)#=>produces 50 numbers between 1 and 10 evenly ranged
print(w)

l=  np.linspace(1,30,100,False)#=>produces 100 numbers between 1 and 30(not included) evenly ranged
print(l)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.    1.29  1.58  1.87  2.16  2.45  2.74  3.03  3.32  3.61  3.9   4.19
  4.48  4.77  5.06  5.35  5.64  5.93  6.22  6.51  6.8   7.09  7.38  7.67
  7.96  8.25  8.54  8.83  9.12  9.41  9.7   9.99 10.28 10.57 10.86 11.15
 11.44 11.73 12.02 12.31 12.6  12.89 13.18 13.47 13.76 14.05 14.34 14.63
 14.92 15.21 15.5  15.79 16.08 16.37 16.66 16.95 17.24 17.53 17.82 18.11
 18.4  18.69 18.98 19.27 1

In [5]:
w=  np.arange(1,30,3)#=>3 is the step  all number with a step  difference of 3 is printed
print(w)

[ 1  4  7 10 13 16 19 22 25 28]


In [11]:
#slicing multidimensional arrays =>rrefer to video
print(twoD_array)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [14]:
#modifying shapes of arrays
ravelled_array=twoD_array.ravel()#return view of original array i.e changes made to original array(cbr)
print(ravelled_array)
flatenned_array=twoD_array.flatten()#returns copy i.e modifies a copy of original array (cbv)
print(flatenned_array)

print(twoD_array.T)#transpose

[0 1 2 0 1 2 0 1 2]
[0 1 2 0 1 2 0 1 2]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [18]:
h=np.zeros([3,4],dtype=int)
print(h)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
p=np.ones([3,4],dtype=int)
print(p)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
print(np.eye(3)) #identity matrix of size 3 by 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
np.random.rand(4,4) #random numbers

array([[0.57595929, 0.54316795, 0.70233667, 0.18710931],
       [0.41163499, 0.79746318, 0.44013979, 0.22447458],
       [0.56710644, 0.25329293, 0.992034  , 0.90980544],
       [0.69402539, 0.5738841 , 0.388039  , 0.4065267 ]])

In [28]:
#matrix multiplication
#conddition => number of columns in A = number of rows in B
matrix1=np.matrix([0,3,5,5,5,2]).reshape(2,3)
matrix2=np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
print(matrix1*matrix2)

product=np.matmul(matrix1,matrix2)
print(product)

print(matrix1@matrix2)

[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]
