In [1]:
import numpy as np
x=np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [3]:
y=np.arange(4,8).reshape(2,2)
print(y)

[[4 5]
 [6 7]]


In [4]:
#horizontally stack these 2 arrays=>condition both should have same number of rows
z=np.hstack((x,y))
print(z)

#horizontal stacking occurs along the second axis thus leadsto increse in number of columns

[[0 1 4 5]
 [2 3 6 7]]


In [5]:
#vertically stack these 2 arrays=>same columns
z=np.vstack((x,y))
print(z)
#vertical stacking occurs along the first axis thus leadsto increse in number of rows

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [7]:
#concatenating
l=np.concatenate((x,y),axis=0)
print(l)#vertical stacking
l=np.concatenate((x,y),axis=1)
print(l)#horizontal stacking

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [8]:
z=np.hstack((x,y))
print(z == l)#checking that the 2 identical at each element

[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
#depth stacking (on 3rd dimension),column stacking,row stacking =>refer video